Avoid sudden exit when no VMA is found for hpcprof-mpi
hpcprof-mpi will exit immediately when no VMA range is found in a load
module. This is true when there's something wrong with either hpcrun or
perhaps hpcstruct.

For instance, with Nekbone, somehow it associates a CCT node with an
invalid vdso load module. With hpcprof, it just shows an error message;
while in hpcprof-mpi it quits immediately with the error message:

ERROR: Analysis::CallPath::noteStaticStructureOnLeaves: failed to find
structure for: S i="1297230" s="0" l="0" strct="0" n="[assoc(NULL (0))
ip(2, 0x7ffd4affda5e) lip()]"
        [../../../../src/lib/analysis/CallPath.cpp:455]
        
This commit doesn't fix the root cause of the problem. Still need
further investigation.